### ISSUE TITLE
Load game broke

### ISSUE THREAD

**Issue by bearda** [ahwmrklas/warpWarp#14]
I don't know whats wrong with it. I'm not seeing any error messages. But it don't actually update the map.

**Comment by ahwmrklas** [comment]
I'll look.
Does a refresh work?
When the layout of the game structure changes I've seen load failures ... but I see actual failures.
My first guess is that I broke this with some recent change. The map only updates when an event is sent. I'm trying to decouple sending a command and receiving a map update response to the command. I want map updates to be asynchronous. So the user sends commands at will and also receives updates for the game at any time.
I'm guessing the load game operation is something I missed. I'll try to look tonight

**Comment by bearda** [comment]
I tried refreshing. I didn't notice anything.

**Comment by ahwmrklas** [comment]
I think I see the problem. (But I'm going to bed)
The server is crashing? You should look for that.
The problem is the history I recently added.
I did it simple. Every command is added to the history ... the problem is a 
restoregame command is huge.... it is the size of a whole game. So I added that to the history and our game size is too big.
We shouldn't add restore game commands to the history (or we should add a truncated version)

**Comment by bearda** [comment]
Wait, the server is crashing? Why did it do that in total silence?

I'll get on it though. Give me... 10 hours? I need to go to work first.

**Comment by ahwmrklas** [comment]
It wasn't a silent crash when I tried it. So perhaps you've seen a
different defect. But scroll back in the output window. It might have
thrown an exception while other threads continued?

**Comment by bearda** [comment]
okay, it wasn't silent. I just didn't scroll through the all of stdout.

anyway, I fixed it.
